<?php
$title = $this->translate('Users');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th><?php echo $this->translate('Name'); ?></th>
</tr>
<?php foreach($users as $user) : ?>
<tr>
    <td>
	<a href="/User/show/<?php echo $user->pkuser; ?>">
	<?php echo $this->escapeHtml($user->firstname) . " " . $this->escapeHtml($user->lastname);?>
	</a>
	</td>
</tr>
<?php endforeach; ?>
</table>