<?php
$title = $this->translate('¨People');
$this->headTitle($title);
?>

<div class = "container">

	<div class = "row">
		<div class = "span12">
			<h2>People</h2>
			<p>Find people to help you out.</p>
		</div>
	</div>

	<div class = "row">
		<span class = "span12">

			<table class = "table table-striped">
				<thead>
					<tr>
						<th>First Name</th>
						<th>Last Name</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($users as $user) : ?>
					<tr>
						<td><a href="/User/show/<?php echo $user->pkuser; ?>"><?php echo $this->escapeHtml($user->firstname) ?></a></td>
						<td><?php echo $this->escapeHtml($user->lastname) ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</span>
</div>

<hr>


