<?php
$title = $this->translate('My profile');
$this->headTitle($title);
?>

<div class = "container">

	<div class = "row" id = "userHead">
		<div class = "span4 offset1">
			<img src="/images/user.jpg" alt = "user">
		</div>

		<div class = "span4 ">
			<h2> <?php echo $user->firstname; ?> <?php echo $user->lastname; ?></h2>

			<p><?php echo $user->description; ?></p>
			<hr>
			<a href="/User/editSkills" class = "btn btn-success btn-large">Edit skills</a>
		</div>

	</div>
	<div class = "row">
		<div class = "span8 offset1">
			<hr>
		</div>

	</div>
	<div class = "row">
		<div class = "span4 offset1">
			<h3>More about me </h3>
			<p><?php echo $user->description; ?></p>
		</div>
		<div class = "span4 ">
			<h3>Skills</h3>
			<?php

			foreach($skills as $skill)
			{
				echo "<p>$skill->description</p>";
				?>
				<div class="progress ">
					<div class="bar" style="width: <?php echo $skill->level; ?>%;">     <?php echo ($skill->name); ?>       </div>
				</div>
				<?php 
			}
			?>
		</div>
	</div>
	<hr>


