<?php
use Zend\Session\Container;

$session = new Container('ideabox');
$isLoggedIn = $session->offsetExists('email');
?>
<!DOCTYPE html>
<html>
	<head>
		<title>IdeaBox</title>
		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<meta http-equiv="Content-Type" content="charset: utf-8" />
	</head>
	<body>
		<div id="page">
			<header>
				<nav>
					<ul>
						<li>
							<a href="/">
							<img id="logo" src="/images/logo.png" alt="logo">
							</a>
						</li>
						<?php if($isLoggedIn): ?>
						<li>
							<a href="/Project/add">
							New project
							</a>
						</li>
						<li>
							<a href="/User/controlPanel">
							Control panel
							</a>
						</li>
						<li>
							<a href="/User/myProfile">
							My profile
							</a>
						</li>
						<?php endif; ?>
						<li>
							<a href="/Project">Projects</a>
						</li>
						<li>
							<a href="/User">People</a>
						</li>
						<li>
						<?php if($isLoggedIn) { ?>
							<a href="/User/logout">Logout</a>
						<?php } else {?>
							<a href="/User/login">Login</a>
						<?php } ?>
						</li>
					</ul>
				</nav>
			</header>
			<div id="content">

				<?php echo $this->content; ?>

			</div>
			<footer>
				<p>
					Copyleft HE-Arc 2012
				</p>
			</footer>
		</div>
	</body>
</html>
