<?php
use Zend\Session\Container;
?>
<!DOCTYPE html>
<html>
	<head>
		<title>IdeaBox</title>
		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<meta http-equiv="Content-Type" content="charset: utf-8" />
	</head>
	<body>
		<div id="page">
			<header>
				<nav>
					<ul>
						<li>
							<a href="/">
							<img id="logo" src="/images/logo.png" alt="logo">
							</a>
						</li>
						<li>
							<a href="/Project/add">
							New project
							</a>
						</li>
						<li>
							<a href="/Project">Projects</a>
						</li>
						<li>
							<a href="/User">People</a>
						</li>
						<li>
							Control panel
						</li>
						<li>
							<a href="/User/myProfile">
							My profile
							</a>
						</li>
						<li>
							<?php
							$session = new Container('ideabox');
							if($session->offsetExists('email'))
							{
						          //echo 'Logged in as '.$session->offsetGet('email');
							  ?><a href="/User/logout">Logout</a><?php
							}
							else
							{?>
								<a href="/User/login">Login</a><?php } ?>
						</li>
					</ul>
				</nav>
			</header>
			<div id="content">

      <?php echo $this->content; ?>

      </div>
			<footer>
				<p>
					Copyleft HE-Arc 2012
				</p>

			</footer>
		</div>
	</body>
</html>
