<?php
$title = 'Create project';
$this->headTitle($title);
?>


<div class = "container">
	<div class = "row">
		<div class = "row">
			<div class = "span3 ">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('Project', array('action' => 'add')));
$form->prepare();
				?>

				<?php echo $this->form()->openTag($form) . PHP_EOL; ?>

				<fieldset>
					<legend><?php echo $this->escapeHtml($title); ?></legend>
					<?php echo $this->formRow($form->get('name')) . PHP_EOL; ?>
					<?php echo $this->formRow($form->get('short_description')) . PHP_EOL; ?>
					<?php echo $this->formRow($form->get('long_description')) . PHP_EOL;  ?>
					<?php echo $this->formRow($form->get('image')) . PHP_EOL; ?>
					<?php echo $this->formInput($form->get('ispublic')) . PHP_EOL; ?>

					<hr>
					<?php echo $this->formInput($form->get('submit')) . PHP_EOL; ?>

				</fieldset>
				<?php echo $this->form()->closeTag($form) . PHP_EOL; ?>
		</div>

	</div>

	<hr>






