<div id="welcomeImagePlaceholder">

				</div>
				<div id="welcomePresentation">
					<h1>Welcome to IdeaBox</h1>
					<ul id="welcomePresentationList">
						<li>
							<h2><a href="Project/add">Submit a project</a></h2>
						</li>
						<li>
							<h2><a href="User">Find collaborateurs</a></h2>
						</li>
						<li>
							<h2><a href="Project">Find innovative projects</a></h2>
						</li>
					</ul>

				</div>
				<div id="descriptionsBlock">
					<div class="description">
						<img class="descriptionImage" src="/images/placeholder.jpg" alt="project">
						<h3 class="descriptionTitle">Submit a project</h3>
						<p>
							Start a project today and become famous with your innovative idea!
						</p>
					</div>
					<div class="description">
						<img class="descriptionImage" src="/images/placeholder.jpg" alt="project">
						<h3 class="descriptionTitle">Find collaborateurs</h3>

						<p>
							Ideabox helps you find people that will make your project famous.
						</p>
					</div>
					<br />
					<div class="description">
						<img class="descriptionImage" src="/images/placeholder.jpg" alt="project">
						<h3 class="descriptionTitle">Help out</h3>

						<p>

							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper.
						</p>
					</div>
					<div class="description">
						<img class="descriptionImage" src="/images/placeholder.jpg" alt="project">
						<h3 class="descriptionTitle">What's this all about</h3>

						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper.
						</p>
					</div>
				</div>