    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="/images/ideas.png" alt="ideas">
          <div class="container">
            <div class="carousel-caption">
              <h1>Ideas</h1>
              <p class="lead">Share your ideas and make them happen</p>
              <a class="btn btn-large btn-primary" href="/User/register">Sign up today</a>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/images/team.png" alt="Team">
          <div class="container">
            <div class="carousel-caption">
              <h1>Find your team</h1>
              <p class="lead">Find your team that will help you make your project leave the sketchbook.</p>
              <a class="btn btn-large btn-primary" href="/User">Learn more</a>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/images/privateIdeas.png" alt="Private Ideas">
          <div class="container">
            <div class="carousel-caption">
              <h1>Don't want to share ?</h1>
              <p class="lead">Memorize your private ideas for later use.</p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->


    <div class = "container">

        <div class="row">
        <span class = "span4">
            <h3>Ideas</h3>
            <p>IdeaBox is based on ideas. Your ideas. We all know you have them. We think it's really important to make ideas become a reality. Here's how it works. You will have to write a detailed description of your idea, and we share it. People may want to help out and you can let them, or not, based on their skills. We hook you up with a team so you can get all those ideas out of your head. Or are you evil and you want to keep all your ideas for yourself? That's fine to, we'll let you. Check out our private ideas sector.</p>
        </span>
        <span class = "span4">
            <h3>People</h3>
            <p>People are important. People make things happen. That's why we're bringing all the talented people in touch all the good ideas. Sometimes we need people with certain skills to get our ideas into reality. That's why we encourage you to show of your skills and maybe help out in some project and we can all make the world a better place (Well that escalated quickly...)</p>
        </span>
        <span class = "span4">
            <h3>Private Ideas</h3>
            <p>People are important. People make things happen. That's why we're bringing all the talented people in touch all the good ideas. Sometimes we need people with certain skills to get our ideas into reality. That's why we encourage you to show of your skills and maybe help out in some project and we can all make the world a better place (Well that escalated quickly...)</p>
        </span>
    </div>

    <hr>