<div id="welcomeImagePlaceholder">

				</div>
				<div id="welcomePresentation">
					<h1>Welcome to IdeaBox</h1>
					<ul id="welcomePresentationList">
						<li>
							<h2>Submit a project</h2>
						</li>
						<li>
							<h2>Find collaborateurs</h2>
						</li>
						<li>
							<h2>Help out</h2>
						</li>
						<li>
							<h2>What's this all about</h2>
						</li>

					</ul>

				</div>
				<div id="descriptionsBlock">
					<div class="description">
						<img class="descriptionImage" src="/images/placeholder.jpg" alt="project">
						<h3 class="descriptionTitle">Submit a project</h3>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper.
						</p>
					</div>
					<div class="description">
						<img class="descriptionImage" src="/images/placeholder.jpg" alt="project">
						<h3 class="descriptionTitle">Find collaborateurs</h3>

						<p>

							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper.
						</p>
					</div>
					<br />
					<div class="description">
						<img class="descriptionImage" src="/images/placeholder.jpg" alt="project">
						<h3 class="descriptionTitle">Help out</h3>

						<p>

							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper.
						</p>
					</div>
					<div class="description">
						<img class="descriptionImage" src="/images/placeholder.jpg" alt="project">
						<h3 class="descriptionTitle">What's this all about</h3>

						<p>

							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. Duis semper.
						</p>
					</div>
				</div>