<?php
$title = $this->translate('My projects');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th><?php echo $this->translate('Short description'); ?></th>
    <th><?php echo $this->translate('Long description'); ?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach($projects as $project) : ?>
<tr>
    <td><?php echo $this->escapeHtml($project->short_description);?></td>
    <td><?php echo $this->escapeHtml($project->long_description);?></td>
</tr>
<?php endforeach; ?>
</table>