<?php
$title = $this->translate('My projects');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th><?php echo $this->translate('Name'); ?></th>
    <th><?php echo $this->translate('Short description'); ?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach($projects as $project) : ?>
<tr>
    <td>
	<a href="/Project/show/<?php echo $project->pkproject; ?>">
	<?php echo $this->escapeHtml($project->name);?>
	</a>
	</td>
    <td><?php echo $this->escapeHtml($project->short_description);?></td>
</tr>
<?php endforeach; ?>
</table>