<?php
$title = 'Join';
$this->headTitle($title);
?>

<div class = "container">
	<div class = "row">
		<div class = "row">
			<div class = "span3 ">
				<?php
				$form = $this->form;
				$form->setAttribute('action', $this->url('Project', array('action' => 'join', 'id' => $id)));
				$form->prepare();
				?>

				<?php echo $this->form()->openTag($form) . PHP_EOL; ?>

				<fieldset>
					<legend><?php echo $this->escapeHtml($title); ?></legend>
					
					<?php echo $this->formSelect($form->get('role')) . PHP_EOL;  ?>
					<?php echo $this->formRow($form->get('comment')) . PHP_EOL; ?>
					
					<hr>
					<?php echo $this->formInput($form->get('submit')) . PHP_EOL; ?>

				</fieldset>
				<hr>
				<?php echo $this->form()->closeTag($form) . PHP_EOL; ?>
		</div>
	</div>










