<?php
$title = $this->translate('Project profile');
$this->headTitle($title);
?>


<div class = "container">
	<div class = "row" id = "userHead">
		<div class = "span4 offset1">
			<img src="<?php echo $project->image; ?>" alt = "user">
		</div>

		<div class = "span4 ">
			<h2><?php echo $project->name; ?></h2>
			
			<p>Posted by <a href="/User/show/<?php echo $owner->pkuser; ?>">
				<?php echo $owner->firstname . " " . $owner->lastname; ?>
			</a></p>
			<p><?php echo $project->short_description; ?></p>
			<p>Created at : <?php echo $project->creationdate; ?></p>
			<hr>
			<a href="/Project/join/<?php echo $project->pkproject; ?>" class = "btn btn-success btn-large"> Join Project!</a>


		</div>

	</div>
	<div class = "row">
		<div class = "span8 offset1">
			<hr>
		</div>

	</div>
	<div class = "row">
		<div class = "span4 offset1">
			<h3>Description</h3>
			<p>Long description</p>
		</div>
		<div class = "span4 ">
			<h3>Members</h3>
			
			<?php
			foreach($members as $member)
			{
				?>
				<p><?php echo $member->role->role ?> : <a href="/User/show/<?php echo $member->pkuser; ?>"><?php echo $member->firstname . " " . $member->lastname; ?></a></p>
				<?php
			}
			?>

		</div>
	</div>


	<hr>

